# Generated by Django 5.2.8 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('IVF & ART', 'IVF & ART'), ('Fertility Preservation', 'Fertility Preservation'), ('Male Factor', 'Male Factor'), ('Gynecology', 'Gynecology'), ('Diagnostics', 'Diagnostics'), ('Surgery', 'Surgery')], max_length=100)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('icon', models.CharField(default='FaHeart', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, help_text='Special badge text', max_length=100)),
                ('success_rate', models.CharField(blank=True, help_text="e.g., '65%'", max_length=20)),
                ('duration', models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50)),
                ('ideal_age', models.CharField(blank=True, help_text="e.g., '25-35 years'", max_length=50)),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='List of process steps with title and description')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefits/advantages')),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
