# Generated by Django 5.2.8 on 2025-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Header image for service detail page', null=True, upload_to='services/'),
        ),
    ]
