# Generated by Django 5.2.8 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Shashwat IVF & Women's Hospital", max_length=200)),
                ('tagline', models.CharField(default="NABH-accredited IVF & Women's Hospital · Ahmedabad", max_length=300)),
                ('description', models.TextField(default="Comprehensive fertility and women's health services under one roof with ethical, transparent care")),
                ('address_line1', models.CharField(default="2nd Floor, Nilkanth Palace, 'B' Opp.Seema Hall", max_length=200)),
                ('address_line2', models.CharField(default='Anandnagar, Satellite', max_length=200)),
                ('city', models.CharField(default='Ahmedabad', max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('pincode', models.CharField(default='380015', max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('front_desk_phone', models.CharField(default='+91 79269 31919', max_length=20)),
                ('appointments_phone', models.CharField(default='+91 75676 72781', max_length=20)),
                ('emergency_phone', models.CharField(default='+91 75676 76297', max_length=20)),
                ('general_email', models.EmailField(default='info@shashwativf.com', max_length=254)),
                ('appointments_email', models.EmailField(default='appointments@shashwativf.com', max_length=254)),
                ('weekday_hours', models.CharField(default='9:00 AM - 7:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(default='10:00 AM - 2:00 PM (Emergency only)', max_length=50)),
                ('towns_reached', models.CharField(default='91+', max_length=10)),
                ('lives_impacted', models.CharField(default='20,000+', max_length=20)),
                ('years_experience', models.CharField(default='20+', max_length=10)),
                ('success_rate', models.CharField(default='65%', max_length=10)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('preferred_service', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
