# Generated by Django 5.2.8 on 2025-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinfo',
            name='address_line1',
            field=models.CharField(default='2nd Floor, Nilkanth Palace', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='address_line2',
            field=models.CharField(default='Prahalad Nagar Road, Opp Seema Hall, Satellite', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='appointments_email',
            field=models.EmailField(default='admin@shashwativf.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='appointments_phone',
            field=models.CharField(default='+91 79269 31919', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='emergency_phone',
            field=models.CharField(default='+91 79269 31919', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='general_email',
            field=models.EmailField(default='admin@shashwativf.com', max_length=254),
        ),
    ]
