# Generated by Django 5.2.8 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualifications', models.TextField()),
                ('experience', models.CharField(help_text="e.g., '20+ years'", max_length=50)),
                ('specialties', models.JSONField(default=list, help_text='List of specialties')),
                ('highlights', models.JSONField(default=list, help_text='List of key highlights')),
                ('bio', models.TextField()),
                ('quote', models.TextField(blank=True)),
                ('is_leader', models.BooleanField(default=False, help_text='Show in leaders section')),
                ('category', models.CharField(choices=[('Doctor', 'Doctor'), ('Consultant', 'Consultant'), ('Specialist', 'Specialist')], default='Doctor', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Upload high-resolution photo (minimum 800x800px)', null=True, upload_to='doctors/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Technician', 'Technician'), ('Administrative', 'Administrative'), ('Support Staff', 'Support Staff')], max_length=50)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
