# Generated by Django 5.2.8 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary of the article')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Dr. Shital Punjabi', max_length=200)),
                ('category', models.CharField(choices=[('Egg Freezing', 'Egg Freezing'), ('IVF Basics', 'IVF Basics'), ('Male Factor', 'Male Factor'), ('IVF Journey', 'IVF Journey'), ("Women's Health", "Women's Health"), ('Support & Wellness', 'Support & Wellness')], max_length=100)),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('featured', models.BooleanField(default=False)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('patient_initials', models.CharField(help_text="e.g., 'A.P.'", max_length=10)),
                ('age', models.IntegerField()),
                ('treatment', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text="e.g., '6 months'", max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('quote', models.TextField()),
                ('story', models.TextField()),
                ('outcome', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('IVF Success', 'IVF Success'), ('Egg Freezing', 'Egg Freezing'), ('Male Factor', 'Male Factor'), ('Gynecology', 'Gynecology'), ('Surgery', 'Surgery')], max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
