# Generated by Django 5.2.8 on 2025-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
