# Generated by Django 5.2.8 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Awards & Recognition', 'Awards & Recognition'), ('Professional Certification', 'Professional Certification'), ('International Training', 'International Training'), ('Institutional Recognition', 'Institutional Recognition'), ('International Faculty', 'International Faculty'), ('Quality Certification', 'Quality Certification')], max_length=50)),
                ('highlight', models.CharField(blank=True, help_text="Special highlight text (e.g., 'Gold Medal Winner')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Excellence',
                'verbose_name_plural': 'Academic Excellence',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Medical Mission', 'Medical Mission'), ('International Faculty', 'International Faculty'), ('Training Program', 'Training Program'), ('Conference Leadership', 'Conference Leadership')], max_length=50)),
                ('beneficiaries', models.CharField(blank=True, help_text="e.g., '200+ patients treated'", max_length=100)),
                ('impact', models.TextField(help_text='Describe the impact and outcomes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Mission',
                'verbose_name_plural': 'Global Missions',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Upload high-resolution photo', upload_to='media/photos/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/')),
                ('category', models.CharField(choices=[('Awards & Recognition', 'Awards & Recognition'), ('International Faculty', 'International Faculty'), ('Global Missions', 'Global Missions'), ('Certifications', 'Certifications'), ('Conferences', 'Conferences')], max_length=50)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Photo',
                'verbose_name_plural': 'Media Photos',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(help_text='YouTube video ID (e.g., dQw4w9WgXcQ)', max_length=50)),
                ('category', models.CharField(choices=[('Patient Stories', 'Patient Stories'), ('Academic Excellence', 'Academic Excellence'), ('Global Missions', 'Global Missions'), ('Facility Tour', 'Facility Tour'), ('Education', 'Education')], max_length=50)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Video',
                'verbose_name_plural': 'Media Videos',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='PressCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('outlet', models.CharField(help_text='Publication name', max_length=200)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('Newspaper', 'Newspaper'), ('Television', 'Television'), ('Online', 'Online'), ('Magazine', 'Magazine')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='press/')),
                ('external_url', models.URLField(blank=True)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Press Coverage',
                'verbose_name_plural': 'Press Coverage',
                'ordering': ['order', '-date'],
            },
        ),
    ]
