# Generated by Django 5.2.8 on 2025-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaphoto',
            name='border_radius',
            field=models.IntegerField(default=12, help_text='Border radius in pixels for rounded corners'),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='collage_position',
            field=models.CharField(choices=[('1x1', '1x1 (Single)'), ('2x1', '2x1 (Wide)'), ('1x2', '1x2 (Tall)'), ('2x2', '2x2 (Square Block)'), ('3x1', '3x1 (Extra Wide)'), ('1x3', '1x3 (Extra Tall)')], default='1x1', help_text='Position in collage layout (grid size)', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='display_size',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail (150x150)'), ('small', 'Small (250x200)'), ('medium', 'Medium (400x300)'), ('large', 'Large (600x450)'), ('extra_large', 'Extra Large (800x600)'), ('full_width', 'Full Width (100% width)'), ('square_small', 'Square Small (200x200)'), ('square_medium', 'Square Medium (300x300)'), ('square_large', 'Square Large (500x500)')], default='medium', help_text='Size of image on frontend', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='height_pixels',
            field=models.IntegerField(default=300, help_text='Custom height in pixels (overrides display_size if set)'),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='width_pixels',
            field=models.IntegerField(default=400, help_text='Custom width in pixels (overrides display_size if set)'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='display_size',
            field=models.CharField(choices=[('small', 'Small (300x200)'), ('medium', 'Medium (400x300)'), ('large', 'Large (600x400)'), ('extra_large', 'Extra Large (800x500)'), ('full_width', 'Full Width (100% width)')], default='medium', help_text='Size of video player on frontend', max_length=20),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='height_pixels',
            field=models.IntegerField(default=300, help_text='Height in pixels for video player'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='width_percentage',
            field=models.IntegerField(default=100, help_text='Width as percentage (1-100) for custom sizing'),
        ),
    ]
