# Generated by Django 5.2.8 on 2025-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaphoto_border_radius_mediaphoto_collage_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload local video file (MP4, WebM, etc.) - Use this OR YouTube ID, not both', null=True, upload_to='media/videos/'),
        ),
        migrations.AlterField(
            model_name='academicexcellence',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalmission',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaphoto',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g., dQw4w9WgXcQ) - Leave empty if uploading local video', max_length=50, null=True),
        ),
    ]
