# Generated by Django 5.2.8 on 2026-04-06 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('media', '0003_mediavideo_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexcellence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='categories.academicexcellencecategory'),
        ),
        migrations.AlterField(
            model_name='globalmission',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='categories.globalmissioncategory'),
        ),
        migrations.AlterField(
            model_name='mediaphoto',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a photo category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='categories.mediaphotocategory'),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a video category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.mediavideocategory'),
        ),
    ]
