# Generated by Django 5.2.8 on 2026-04-06 11:32

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_data(apps, schema_editor):
    # Mapping of (Media Model, Category Model)
    mappings = [
        ('AcademicExcellence', 'AcademicExcellenceCategory'),
        ('GlobalMission', 'GlobalMissionCategory'),
        ('MediaPhoto', 'MediaPhotoCategory'),
        ('MediaVideo', 'MediaVideoCategory'),
    ]
    
    for model_name, cat_model_name in mappings:
        Model = apps.get_model('media', model_name)
        CategoryModel = apps.get_model('categories', cat_model_name)
        
        for record in Model.objects.all():
            # If the old category field (now renamed to category_old) has data
            if hasattr(record, 'category_old') and record.category_old:
                category_name = record.category_old.strip()
                if category_name:
                    # Get or create the category object
                    cat_obj, _ = CategoryModel.objects.get_or_create(name=category_name)
                    # Link it to the new ForeignKey field
                    record.category = cat_obj
                    record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('media', '0003_mediavideo_video_file_and_more'),
    ]

    operations = [
        # 1. Rename existing 'category' CharField to 'category_old'
        migrations.RenameField(
            model_name='academicexcellence',
            old_name='category',
            new_name='category_old',
        ),
        migrations.RenameField(
            model_name='globalmission',
            old_name='category',
            new_name='category_old',
        ),
        migrations.RenameField(
            model_name='mediaphoto',
            old_name='category',
            new_name='category_old',
        ),
        migrations.RenameField(
            model_name='mediavideo',
            old_name='category',
            new_name='category_old',
        ),

        # 2. Add new 'category' ForeignKey field (nullable)
        migrations.AddField(
            model_name='academicexcellence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='categories.academicexcellencecategory'),
        ),
        migrations.AddField(
            model_name='globalmission',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='categories.globalmissioncategory'),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a photo category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='categories.mediaphotocategory'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a video category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.mediavideocategory'),
        ),

        # 3. Migrate data from 'category_old' to 'category'
        migrations.RunPython(migrate_category_data),

        # 4. Remove 'category_old'
        migrations.RemoveField(
            model_name='academicexcellence',
            name='category_old',
        ),
        migrations.RemoveField(
            model_name='globalmission',
            name='category_old',
        ),
        migrations.RemoveField(
            model_name='mediaphoto',
            name='category_old',
        ),
        migrations.RemoveField(
            model_name='mediavideo',
            name='category_old',
        ),
    ]
