# Generated by Django 5.2.8 on 2026-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_academicexcellence_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexcellence',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalmission',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaphoto',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
