# Generated by Django 5.2.8 on 2026-04-06 12:00

import re
from urllib.parse import parse_qs, urlparse
from django.db import migrations, models


YOUTUBE_ID_RE = re.compile(r'^[A-Za-z0-9_-]{11}$')


def extract_youtube_video_id(value):
    if not value:
        return None

    candidate = str(value).strip()
    if not candidate:
        return None

    parsed = urlparse(candidate)
    video_id = None

    if parsed.scheme and parsed.netloc:
        host = parsed.netloc.lower()
        path_parts = [part for part in parsed.path.split('/') if part]

        if host in {'youtu.be', 'www.youtu.be'}:
            video_id = path_parts[0] if path_parts else None
        elif host.endswith('youtube.com') or host.endswith('youtube-nocookie.com'):
            if parsed.path == '/watch':
                video_id = parse_qs(parsed.query).get('v', [None])[0]
            elif len(path_parts) >= 2 and path_parts[0] in {'embed', 'shorts', 'live', 'v'}:
                video_id = path_parts[1]
    else:
        video_id = candidate

    if video_id:
        video_id = video_id.split('&', 1)[0].split('?', 1)[0].strip()

    return video_id if video_id and YOUTUBE_ID_RE.fullmatch(video_id) else None


def normalize_media_contract(apps, schema_editor):
    MediaVideo = apps.get_model('media', 'MediaVideo')
    MediaPhoto = apps.get_model('media', 'MediaPhoto')

    for video in MediaVideo.objects.all():
        update_fields = []
        normalized_id = extract_youtube_video_id(video.youtube_id)
        if normalized_id and normalized_id != video.youtube_id:
            video.youtube_id = normalized_id
            update_fields.append('youtube_id')

        if video.width_percentage == 100 and video.height_pixels == 300:
            video.width_percentage = None
            video.height_pixels = None
            update_fields.extend(['width_percentage', 'height_pixels'])

        if update_fields:
            video.save(update_fields=list(dict.fromkeys(update_fields)))

    for photo in MediaPhoto.objects.all():
        if photo.width_pixels == 400 and photo.height_pixels == 300:
            photo.width_pixels = None
            photo.height_pixels = None
            photo.save(update_fields=['width_pixels', 'height_pixels'])


def reverse_normalize_media_contract(apps, schema_editor):
    MediaVideo = apps.get_model('media', 'MediaVideo')
    MediaPhoto = apps.get_model('media', 'MediaPhoto')

    MediaVideo.objects.filter(width_percentage__isnull=True).update(width_percentage=100)
    MediaVideo.objects.filter(height_pixels__isnull=True).update(height_pixels=300)
    MediaPhoto.objects.filter(width_pixels__isnull=True).update(width_pixels=400)
    MediaPhoto.objects.filter(height_pixels__isnull=True).update(height_pixels=300)


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_academicexcellence_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaphoto',
            name='height_pixels',
            field=models.IntegerField(blank=True, help_text='Optional custom height in pixels. Leave empty to use display size presets.', null=True),
        ),
        migrations.AlterField(
            model_name='mediaphoto',
            name='width_pixels',
            field=models.IntegerField(blank=True, help_text='Optional custom width in pixels. Leave empty to use display size presets.', null=True),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='height_pixels',
            field=models.IntegerField(blank=True, help_text='Optional custom height in pixels. Leave empty to use display size presets.', null=True),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='width_percentage',
            field=models.IntegerField(blank=True, help_text='Optional custom width percentage (1-100). Leave empty to use display size presets.', null=True),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Paste a YouTube URL or video ID (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)', max_length=255, null=True),
        ),
        migrations.RunPython(normalize_media_contract, reverse_normalize_media_contract),
    ]
