# Generated by Django 5.2.8 on 2026-04-06 12:34

from django.db import migrations, models


def populate_content_sources(apps, schema_editor):
    MediaVideo = apps.get_model('media', 'MediaVideo')
    PressCoverage = apps.get_model('media', 'PressCoverage')

    for video in MediaVideo.objects.all():
        video.content_source = 'video_file' if video.video_file else 'youtube'
        video.save(update_fields=['content_source'])

    for article in PressCoverage.objects.all():
        article.content_source = 'image'
        article.save(update_fields=['content_source'])


def reverse_populate_content_sources(apps, schema_editor):
    MediaVideo = apps.get_model('media', 'MediaVideo')
    PressCoverage = apps.get_model('media', 'PressCoverage')

    MediaVideo.objects.update(content_source='youtube')
    PressCoverage.objects.update(content_source='image')


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_mediaphoto_height_pixels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavideo',
            name='content_source',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('video_file', 'Uploaded Video File')], default='youtube', help_text='Choose how this video should be provided.', max_length=20),
        ),
        migrations.AddField(
            model_name='presscoverage',
            name='content_source',
            field=models.CharField(choices=[('image', 'Image'), ('youtube', 'YouTube Video'), ('video_file', 'Uploaded Video File')], default='image', help_text='Choose whether this press coverage uses an image, YouTube video, or uploaded video file.', max_length=20),
        ),
        migrations.AddField(
            model_name='presscoverage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a local video file for this press item.', null=True, upload_to='press/videos/'),
        ),
        migrations.AddField(
            model_name='presscoverage',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Paste a YouTube URL or video ID for this press item.', max_length=255, null=True),
        ),
        migrations.RunPython(populate_content_sources, reverse_populate_content_sources),
    ]
