# Generated by Django 5.2.8 on 2026-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_mediavideo_content_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavideo',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover image for uploaded video files.', null=True, upload_to='media/video-thumbnails/'),
        ),
        migrations.AddField(
            model_name='presscoverage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover image for uploaded press videos.', null=True, upload_to='press/video-thumbnails/'),
        ),
    ]
