# Generated by Django 5.2.8 on 2026-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Shashwat IVF & Women's Hospital", max_length=255)),
                ('meta_title', models.CharField(default="Shashwat IVF & Women's Hospital | Best IVF Centre in Ahmedabad", help_text='The title that appears in Google search and WhatsApp previews.', max_length=255)),
                ('meta_description', models.TextField(default="Shashwat IVF & Women's Hospital is the leading fertility clinic in Ahmedabad providing advanced IVF treatments, ICSI, Egg Freezing, and comprehensive women's healthcare.", help_text='The description that appears in Google search and WhatsApp previews.')),
                ('og_image', models.ImageField(blank=True, help_text='The image that appears when you share the website link on WhatsApp/Facebook (Recommended 1200x630px).', null=True, upload_to='site_config/')),
                ('favicon', models.FileField(blank=True, help_text='The small icon in the browser tab.', null=True, upload_to='site_config/')),
                ('contact_phone', models.CharField(default='+91 99252 44431', max_length=20)),
                ('contact_email', models.EmailField(default='dritalpunjabi@gmail.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
